version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: revendas-mysql
      working_dir: /application
      volumes:
        - ./infra:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=revendas-db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: revendas-webserver
      working_dir: /application
      volumes:
          - ./sistema-revendas:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: ./phpdocker/php-fpm
      container_name: revendas-php-fpm
      working_dir: /application
      volumes:
        - ./sistema-revendas:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    redis:
      container_name: revendas-redis
      restart: always
      build: ./redis
      working_dir: /application
      volumes:
        - ./redis:/application
      ports:
        - "6379:6379"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: revendas-phpmyadmin
        links:
          - mysql
        ports:
          - 8081:80
        environment:
          - PMA_ARBITRARY=1     